### ISSUE TITLE
what is the license?

### ISSUE THREAD

**Issue by mrexodia** [vadimkotov/winapi-json#1]
Hey, I'm interested in using this as part of [x64dbg](http://x64dbg.com), but it has no license. What is the license?

**Comment by vadimkotov** [comment]
Hi. It's GPL 3.0, I couldn't be bothered to add it, but will soon. So knock
yourself out. Also if you have any specific requests do let me know, I'm
trying to make this project useful.

On Jun 30, 2017 6:19 PM, "Duncan Ogilvie" <notifications@github.com> wrote:

Hey, I'm interested in using this as part of x64dbg <http://x64dbg.com>,
but it has no license. What is the license?

**Comment by vadimkotov** [comment]
Added the license info https://github.com/vadimkotov/winapi-json/blob/master/LICENSE.txt
