### ISSUE TITLE
BOOL WINAPI is not a type

### ISSUE THREAD

**Issue by mrexodia** [vadimkotov/winapi-json#2]
`"return_type": "BOOL WINAPI"`

WINAPI is a define for `__declspec(stdcall)`, it's not part of the return type, but rather the calling convention used.

**Comment by vadimkotov** [comment]
I'm on vacation till the 10-th of July will fix it once I'm back

**Comment by vadimkotov** [comment]
Fixed
https://github.com/vadimkotov/winapi-json/commit/62ec35f5bfbfbb96e2466708673f702e3f945ea6
