### ISSUE TITLE
More open license?

### ISSUE THREAD

**Issue by marler8997** [vadimkotov/winapi-json#3]
I was considering using these JSON files to generate bindings for the Zig language, however, I realized this repository uses the GPL 3.0 license.  Would you consider releasing these files with a less restrictive license, such as MIT/BSD/Apache/etc?

**Comment by vadimkotov** [comment]
Hi Jonathan,

Can do, what license do you think would be best here?

**Comment by marler8997** [comment]
The 3 that I listed above are pretty standard and lenient enough, you would be fine choosing any of them.  If you want me to pick one I would say go with MIT.

**Comment by vadimkotov** [comment]
Hi Jonathan,

Apologies for the delayed response. After some consideration I've changed it to Apache2.

Cheers,
Vadim
